version: 2
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/php:7.1-node-browsers
    - image: circleci/mysql:5.7
  environment:
    - AWS_REGION: us-east-1
    - APP_DEBUG: true
    - APP_ENV: testing
    - APP_KEY: base64:cNWYphm1YWH+RGYFLZpn6MBKj/TRiMm46KbuWA8Ei8c=
    - DB_DATABASE: circle_test
    - DB_USERNAME: root
    - MYSQL_ALLOW_EMPTY_PASSWORD: true
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install pdo_mysql
          command: |
            sudo apt update
            sudo docker-php-ext-install pdo_mysql
            sudo docker-php-ext-enable pdo_mysql
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      # run seeding
      - run: php artisan migrate
      - run: php artisan db:seed
      # run test
      - run: ./vendor/bin/phpunit
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install awsebcli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
    - run:
        name: eb deploy
        command: eb deploy konomachi-sports
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
